/** Item catalog generated by tools/build_catalog.py from the game's data.win. */

export type CatalogKind = "object" | "weapon" | "armor";

export interface CatalogItem {
  key: string;
  kind: CatalogKind;
  /** Only for objects: the GameMaker object name written as the record head, e.g. "o_inv_bear_fat". */
  objectName?: string;
  name: string;
  category: string;
  subcategory: string;
  material: string;
  tags: string;
  price: number | null;
  /** Objects only: max stack size from the item table, null when the item does not stack. */
  stacks?: number | null;
  /** Objects only: freshness for food, effect duration, and whether the item holds other items. */
  fresh?: number | null;
  effectDuration?: number | null;
  container?: boolean;
  rarity?: string;
  tier?: number | null;
  maxDuration?: number | null;
  /** Equipment only: table slot ("sword", "Ring"), armor class, weapon range, and the stat columns. */
  slot?: string;
  armorClass?: string;
  range?: number | null;
  stats?: Record<string, number>;
  hidden: boolean;
  w: number;
  h: number;
  sprite?: string;
}

export type Template = Record<string, unknown>;

export interface Catalog {
  cellPixels: number;
  source: string;
  items: CatalogItem[];
  byKey: Map<string, CatalogItem>;
  /** Property templates harvested from real saves by tools/harvest_templates.py, keyed by object id. */
  templates: Record<string, Template>;
}

export async function loadCatalog(): Promise<Catalog> {
  const [itemsResponse, templatesResponse] = await Promise.all([
    fetch(`${import.meta.env.BASE_URL}catalog/items.json`),
    fetch(`${import.meta.env.BASE_URL}catalog/templates.json`),
  ]);
  if (!itemsResponse.ok) throw new Error(`Could not load the item catalog (${itemsResponse.status}).`);
  const raw = (await itemsResponse.json()) as Omit<Catalog, "byKey" | "templates">;
  const templates = templatesResponse.ok ? ((await templatesResponse.json()) as Record<string, Template>) : {};
  return { ...raw, templates, byKey: new Map(raw.items.map((item) => [item.key, item])) };
}

export function spriteUrl(item: CatalogItem | undefined): string | undefined {
  return item?.sprite ? `${import.meta.env.BASE_URL}sprites/${item.sprite}` : undefined;
}

/** Catalog key for a record head: objects are "o_inv_<key>", equipment is keyed by its table name. */
export function catalogKeyForHead(head: string): string {
  return head.startsWith("o_inv_") ? head.slice(6) : head;
}

/** Items the picker can generate from scratch: every visible object except coins, plus all weapons and armor. */
export function isCatalogAddable(item: CatalogItem): boolean {
  if (item.hidden) return false;
  if (item.kind === "object") return item.category !== "currency";
  return true;
}
